// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKEIyQer3b8C9L3-EPFjPpYVVP2FUm_Mk',
    appId: '1:647489145856:web:4f11daee43c5e04bf35ce5',
    messagingSenderId: '647489145856',
    projectId: 'crudflutter-a8b8b',
    authDomain: 'crudflutter-a8b8b.firebaseapp.com',
    storageBucket: 'crudflutter-a8b8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz3h3W3ArLhFwbb19xIvZpaHJloT9YdLw',
    appId: '1:647489145856:android:ddd47b47debcaffaf35ce5',
    messagingSenderId: '647489145856',
    projectId: 'crudflutter-a8b8b',
    storageBucket: 'crudflutter-a8b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-mLQfnZnUjuVpV7PFi4BYPZwB1sKNXI',
    appId: '1:647489145856:ios:782565486d6596f2f35ce5',
    messagingSenderId: '647489145856',
    projectId: 'crudflutter-a8b8b',
    storageBucket: 'crudflutter-a8b8b.appspot.com',
    iosClientId:
        '647489145856-hjqn239u6u98gnaq5sri9u875kmuq3r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-mLQfnZnUjuVpV7PFi4BYPZwB1sKNXI',
    appId: '1:647489145856:ios:2348dbdb51e3f765f35ce5',
    messagingSenderId: '647489145856',
    projectId: 'crudflutter-a8b8b',
    storageBucket: 'crudflutter-a8b8b.appspot.com',
    iosClientId:
        '647489145856-0j98c24d1hckb096vafm91rph1b9cpes.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase.RunnerTests',
  );
}
